### PR TITLE
Room data cleaning

### PR DESCRIPTION
**Pull request by yvesfracari**
This pull request creates a script to clean data related with the room of the houses and a notebook to explain it.

### CODE REVIEW

**Comment by yvesfracari** [comment]
<p>I agree, but I didn't find a better way to clean this variable.</p>

---

 <a href='https://app.reviewnb.com/neo-empresarial/house_pricing_challenge/pull/8/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yvesfracari** [comment]
<p>Humm, you have a good point, I will undo this change!</p>

---

 <a href='https://app.reviewnb.com/neo-empresarial/house_pricing_challenge/pull/8/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yvesfracari** [comment]
<p>I don't think so! The format of the curve it's affected with because of the few values!</p>

---

 <a href='https://app.reviewnb.com/neo-empresarial/house_pricing_challenge/pull/8/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yvesfracari** [comment]
<p>I aggre with you, but some variables can't tell us mush normally. And I didn't find a way to clean this varieble better</p>

---

 <a href='https://app.reviewnb.com/neo-empresarial/house_pricing_challenge/pull/8/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Stefenon** [comment]
<p>I analyzed it again and you're point of view makes sense!</p>

---

 <a href='https://app.reviewnb.com/neo-empresarial/house_pricing_challenge/pull/8/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
